$ANSIBLE_VAULT;1.1;AES256
62623737643134386163343466386436326363383735323730306638393831633430636461393432
3233353562323833646165663038376163316666373065320a636365653263623935346133363230
35353835316663616433656366343534336163613965353365316263663737373962623566323064
3833616463336337610a346563303431336161373533663335346230663866643936313534313835
35353131366134663339633739373335613731383630623837313562396361643266626365653434
66313337373738626236396266343839626536633665343464363065383830333231633938613062
31363032333530373762643063333666313762636230343031383463336235666634373563663664
31373063663235383633
